--- 
title: "CovidInsights"
author: "Zhe Hou & Jingfei Fang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
COVID-19 (SARS-CoV-2) has swept across the globe, causing countless deaths and enormous impact on people's life. As up to 2021/12/11, COVID-19 has caused around 5.3 million deaths worldwide. Because of COVID-19, people are wearing masks all the time, many businesses went bankrupt, and transportation (especially between countries) has been heavily reduced. There are more changes COVID-19 has brought into our life, and we are dedicated to investigate the impact of COVID-19 on human life and economy in the U.S. which is among the most impacted countries. 

Specifically, we use the data aggregated by Carnegie Mellon University, and it contain various kinds of data, such as doctor visits and hospital related data, bar and restaurant visits data, Google search data. Through analyzing these data, we not only gained some insights of covid-19 pandemic and its influence on people and economy, but also found some interesting patterns of people's behaviors during pandemic. So let's start now!
